name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # بيحدث نفسه كل يوم الساعة 12 بالليل
  workflow_dispatch: # بيسمح لك تشغله يدوي في أي وقت
push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MohamedRaghebOmer
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Africa/Cairo
          # الإضافات الجمالية
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
